[package]
name = "cakify-mcp"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
async-channel.workspace = true
cakify-core = { path = "../cakify-core" }
cakify-storage = { path = "../cakify-storage" }
process-wrap.workspace = true
rmcp.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
